-- 为已有库补齐表/字段注释（与 schema.sql 一致）
-- 执行: mysql -uroot -proot linkx_im < fix_table_comments.sql
USE linkx_im;

-- ========== 表注释（P0 等脚本建表时未带 COMMENT）==========
ALTER TABLE sys_file_hash_blacklist COMMENT = '文件哈希黑名单';
ALTER TABLE sys_report COMMENT = '用户举报工单表';
ALTER TABLE sys_sensitive_hit_log COMMENT = '敏感词命中记录';
ALTER TABLE sys_sensitive_word COMMENT = '敏感词库';
ALTER TABLE sys_user_notification COMMENT = '用户站内通知';

-- ========== sys_admin ==========
ALTER TABLE sys_admin
    MODIFY COLUMN last_login_time DATETIME DEFAULT NULL COMMENT '最后登录时间',
    MODIFY COLUMN last_login_ip VARCHAR(64) DEFAULT NULL COMMENT '最后登录IP',
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 0未删除 1已删除';

-- ========== sys_app_release ==========
ALTER TABLE sys_app_release
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN platform VARCHAR(32) NOT NULL COMMENT '平台 win/mac/linux',
    MODIFY COLUMN version VARCHAR(32) NOT NULL COMMENT '版本号',
    MODIFY COLUMN download_url VARCHAR(500) DEFAULT NULL COMMENT '下载地址',
    MODIFY COLUMN release_notes VARCHAR(2000) DEFAULT NULL COMMENT '更新说明',
    MODIFY COLUMN force_update TINYINT DEFAULT 0 COMMENT '是否强制更新 0否 1是',
    MODIFY COLUMN published TINYINT DEFAULT 0 COMMENT '是否发布 0否 1是',
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ========== sys_audit_log ==========
ALTER TABLE sys_audit_log
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN admin_id BIGINT DEFAULT NULL COMMENT '操作管理员ID',
    MODIFY COLUMN admin_username VARCHAR(64) DEFAULT NULL COMMENT '操作管理员用户名',
    MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '动作',
    MODIFY COLUMN target_type VARCHAR(64) DEFAULT NULL COMMENT '目标类型',
    MODIFY COLUMN target_id VARCHAR(64) DEFAULT NULL COMMENT '目标ID',
    MODIFY COLUMN detail VARCHAR(1000) DEFAULT NULL COMMENT '详情',
    MODIFY COLUMN client_ip VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== sys_blacklist ==========
ALTER TABLE sys_blacklist
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN blacklist_user_id BIGINT NOT NULL COMMENT '被拉黑用户ID',
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== sys_friend ==========
ALTER TABLE sys_friend
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN friend_id BIGINT NOT NULL COMMENT '好友ID',
    MODIFY COLUMN remark VARCHAR(100) DEFAULT NULL COMMENT '备注',
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== sys_friend_request ==========
ALTER TABLE sys_friend_request
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN from_user_id BIGINT NOT NULL COMMENT '申请人ID',
    MODIFY COLUMN to_user_id BIGINT NOT NULL COMMENT '被申请人ID',
    MODIFY COLUMN message VARCHAR(255) DEFAULT NULL COMMENT '验证消息',
    MODIFY COLUMN status TINYINT DEFAULT 0 COMMENT '状态 0待处理 1已同意 2已拒绝',
    MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== im_session ==========
ALTER TABLE im_session
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '会话ID';

-- ========== sys_file_hash_blacklist ==========
ALTER TABLE sys_file_hash_blacklist
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN content_hash VARCHAR(128) NOT NULL COMMENT '文件内容哈希 SHA-256',
    MODIFY COLUMN reason VARCHAR(255) DEFAULT NULL COMMENT '拉黑原因',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0禁用 1启用',
    MODIFY COLUMN create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== sys_report ==========
ALTER TABLE sys_report
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '举报单ID',
    MODIFY COLUMN reporter_user_id BIGINT NOT NULL COMMENT '举报人用户ID',
    MODIFY COLUMN target_type VARCHAR(32) NOT NULL COMMENT '目标类型 USER/MESSAGE/GROUP/FILE',
    MODIFY COLUMN target_id VARCHAR(64) NOT NULL COMMENT '目标ID',
    MODIFY COLUMN reason_category VARCHAR(32) NOT NULL COMMENT '原因分类 SPAM/ABUSE/FRAUD/PORNOGRAPHY/OTHER',
    MODIFY COLUMN reason_detail VARCHAR(1000) DEFAULT NULL COMMENT '补充说明',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 0 COMMENT '0待处理 1处理中 2已结案 3已驳回',
    MODIFY COLUMN handler_admin_id BIGINT DEFAULT NULL COMMENT '处理管理员ID',
    MODIFY COLUMN resolution VARCHAR(32) DEFAULT NULL COMMENT '处置结果 WARN/DELETE_CONTENT/BAN_USER/BAN_GROUP/DISMISS',
    MODIFY COLUMN resolution_note VARCHAR(1000) DEFAULT NULL COMMENT '处理说明',
    MODIFY COLUMN notify_reporter TINYINT NOT NULL DEFAULT 1 COMMENT '是否通知举报人 0否 1是',
    MODIFY COLUMN reporter_notified TINYINT NOT NULL DEFAULT 0 COMMENT '是否已通知举报人',
    MODIFY COLUMN handled_time DATETIME DEFAULT NULL COMMENT '处理时间',
    MODIFY COLUMN create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ========== sys_sensitive_word ==========
ALTER TABLE sys_sensitive_word
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN word VARCHAR(128) NOT NULL COMMENT '敏感词',
    MODIFY COLUMN match_mode TINYINT NOT NULL DEFAULT 1 COMMENT '1包含 2全词匹配',
    MODIFY COLUMN category VARCHAR(32) DEFAULT 'DEFAULT' COMMENT '分类',
    MODIFY COLUMN action TINYINT NOT NULL DEFAULT 1 COMMENT '1拦截 2仅记录',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0禁用 1启用',
    MODIFY COLUMN create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ========== sys_sensitive_hit_log ==========
ALTER TABLE sys_sensitive_hit_log
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '触发用户ID',
    MODIFY COLUMN word_id BIGINT DEFAULT NULL COMMENT '命中词ID',
    MODIFY COLUMN matched_word VARCHAR(128) DEFAULT NULL COMMENT '命中词快照',
    MODIFY COLUMN content_snippet VARCHAR(500) DEFAULT NULL COMMENT '内容摘要',
    MODIFY COLUMN source VARCHAR(32) NOT NULL DEFAULT 'CHAT_SEND' COMMENT '来源',
    MODIFY COLUMN blocked TINYINT NOT NULL DEFAULT 0 COMMENT '是否已拦截',
    MODIFY COLUMN message_id BIGINT DEFAULT NULL COMMENT '关联消息ID',
    MODIFY COLUMN create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ========== sys_user_notification ==========
ALTER TABLE sys_user_notification
    MODIFY COLUMN id BIGINT NOT NULL COMMENT 'ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '接收用户ID',
    MODIFY COLUMN title VARCHAR(128) NOT NULL COMMENT '标题',
    MODIFY COLUMN content VARCHAR(1000) NOT NULL COMMENT '内容',
    MODIFY COLUMN biz_type VARCHAR(32) DEFAULT NULL COMMENT '业务类型 REPORT_RESULT/APPEAL/SYSTEM',
    MODIFY COLUMN biz_id VARCHAR(64) DEFAULT NULL COMMENT '业务ID',
    MODIFY COLUMN read_flag TINYINT NOT NULL DEFAULT 0 COMMENT '0未读 1已读',
    MODIFY COLUMN create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';